import {
    FiHome,
    FiLogIn,
    FiUserPlus,
    FiUser,
    FiPackage,
    FiShoppingCart,
    FiAlertTriangle,
    FiTag,
    FiImage,
    FiSettings,
    FiMessageSquare,
    FiLayout,
    FiUsers,
    FiGrid,
    FiLogOut,
    FiHeart,
    FiRefreshCw,
} from 'react-icons/fi';

const iconMap = {
    Home: FiHome,
    Login: FiLogIn,
    UserPlus: FiUserPlus,
    User: FiUser,
    Package: FiPackage,
    ShoppingCart: FiShoppingCart,
    AlertTriangle: FiAlertTriangle,
    Tag: FiTag,
    Image: FiImage,
    Settings: FiSettings,
    MessageSquare: FiMessageSquare,
    LayoutDashboard: FiLayout,
    Users: FiUsers,
    Grid: FiGrid,
    LogOut: FiLogOut,
    Heart: FiHeart,
    RotateCcw: FiRefreshCw,
};

export default iconMap;
